In [1]:
import numpy as np 
import cv2
import time

def main():
    windowName='Live Video Feed'
    cv2.namedWindow(windowName)
    cap=cv2.VideoCapture(0)
    if cap.isOpened():
        ret,frame=cap.read()
    else:
        ret=False
    rows,columnes,channels=frame.shape
    angle=0
    scale=1
    while True:
        ret,frame=cap.read()
        if angle==360:
            angle=0
        R=cv2.getRotationMatrix2D((columnes/2,rows/2),angle,scale)
        print(R)
        output=cv2.warpAffine(frame,R,(columnes,rows))
        cv2.imshow(windowName,output)
        angle=angle+1
        time.sleep(0.01)
        if cv2.waitKey(20)==27:
            break
    cv2.destroyAllWindows()
    cv2.destroyWindow(windowName)
    
main()
    

[[ 1.  0.  0.]
 [-0.  1.  0.]]
[[ 0.9998477   0.01745241 -4.13983999]
 [-0.01745241  0.9998477   5.62132322]]
[[ 0.99939083  0.0348995  -8.18094385]
 [-0.0348995   0.99939083 11.31404046]]
[[  0.99862953   0.05233596 -12.12208062]
 [ -0.05233596   0.99862953  17.07641766]]
[[  0.99756405   0.06975647 -15.96204978]
 [ -0.06975647   0.99756405  22.90669954]]
[[  0.9961947    0.08715574 -19.69968165]
 [ -0.08715574   0.9961947   28.80311014]]
[[  0.9945219    0.10452846 -23.3338377 ]
 [ -0.10452846   0.9945219   34.76385336]]
[[  0.99254615   0.12186934 -26.86341094]
 [ -0.12186934   0.99254615  40.7871135 ]]
[[  0.99026807   0.1391731  -30.28732623]
 [ -0.1391731    0.99026807  46.87105581]]
[[  0.98768834   0.15643447 -33.6045406 ]
 [ -0.15643447   0.98768834  53.01382707]]
[[  0.98480775   0.17364818 -36.8140436 ]
 [ -0.17364818   0.98480775  59.21355613]]
[[  0.98162718   0.190809   -39.91485759]
 [ -0.190809     0.98162718  65.46835449]]
[[  0.9781476    0.20791169 -42.90603803]
 [ -

 [-9.97564050e-01 -6.97564737e-02  5.75962050e+02]]
[[-8.71557427e-02  9.96194698e-01  1.08803110e+02]
 [-9.96194698e-01 -8.71557427e-02  5.79699682e+02]]
[[-1.04528463e-01  9.94521895e-01  1.14763853e+02]
 [-9.94521895e-01 -1.04528463e-01  5.83333838e+02]]
